all:
  children:
    hypervisors:
      hosts:
        host_a:
          ansible_host: 192.168.1.161
          vxlan_remote_ip: 192.168.1.134

        host_b:
          ansible_host: 192.168.1.134
          vxlan_remote_ip: 192.168.1.161

      vars:
        ansible_user: kiasoh

        bridge_name: vm-br0
        vxlan_name: vxlan100
        vxlan_id: 100
        vxlan_port: 4789
        vxlan_parent_interface: wlan0
